version: '3.8'

services:
  # go_app
  app:
    container_name: asset_sim_app
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/dockerfiles/app/Dockerfile
    volumes: # マウント
      - ./app:/usr/local/go/src/web/app
      - .env:/usr/local/go/src/web/app/.env
    tty: true # コンテナの永続化
    depends_on:
      - db
    ports:
      - 8080:8080

  # postgresql
  db:
    container_name: asset_sim_db
    build:
      context: .
      dockerfile: ./build/dockerfiles/db/Dockerfile
    environment:
      # - POSTGRES_DB=${DB_DATABASE_NAME}
      # - POSTGRES_USER=${DB_USER}
      # - POSTGRES_PASSWORD=${DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: always

volumes:
  db-store:
